application:
  name: giraone-test-bridge
  url: "http://www.heise.de"

giraone:
  hostname: "192.168.178.38"
  username: "User"
  password: "!Ncc1701D"

mqtt:
  broker: "192.168.178.69"
  port: 1883
  username: "mqtt-dev"
  password: "mqtt-pass"

logging:
  level:
    root: INFO
    de:
      matgroe: debug