application:
  name: giraone-mqtt-bridge
  url: "https://github.com/matgroe/giraone-mqtt-bridge"

giraone:
  server: ${GIRAONE_SERVER:#{null}}
  user: ${GIRAONE_USER:#{null}}
  password: ${GIRAONE_PASSWORD:#{null}}

mqtt:
  broker: ${MQTT_BROKER:#{null}}
  port: ${MQTT_PORT:1883}
  user: ${MQTT_USER:#{null}}
  password: ${MQTT_PASSWORD:#{null}}

logging:
  level:
    root: INFO
    de:
      matgroe: ${LOG_LEVEL:INFO}