/*
 * GiraOne Bridge
 * Copyright (C) 2025 Matthias Gröger
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.matgroe.bridge;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;
import static org.mockito.Mockito.when;

import de.matgroe.giraone.GiraOneTestDataProvider;
import de.matgroe.giraone.client.GiraOneClient;
import de.matgroe.giraone.client.types.GiraOneDataPoint;
import de.matgroe.giraone.client.types.GiraOneProject;
import java.util.Optional;
import java.util.stream.Stream;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.mockito.Mockito;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** Testclass for @{@link GiraOneChannelMqttTopicMapper} */
public class TopicNameMapperTest {
  private final Logger logger = LoggerFactory.getLogger(TopicNameMapperTest.class);

  static GiraOneClient giraOneClient = Mockito.mock(GiraOneClient.class);

  GiraOneProject giraOneProject;

  static GiraOneChannelMqttTopicMapper giraOneChannelMqttTopicMapper;

  @BeforeAll
  static void init() {
    when(giraOneClient.getGiraOneProject())
        .thenReturn(GiraOneTestDataProvider.createGiraOneProject());
    when(giraOneClient.lookupGiraOneDeviceConfiguration())
        .thenReturn(GiraOneTestDataProvider.createGiraOneDeviceConfiguration());

    giraOneChannelMqttTopicMapper =
        new GiraOneChannelMqttTopicMapper("g1-junit", giraOneClient.getGiraOneProject());
  }

  @BeforeEach
  void setUp() {
    giraOneProject = giraOneClient.getGiraOneProject();
  }

  private static Stream<Arguments> providePairStateTopicNameOfChannelAndDataPoint() {
    return Stream.of(
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-4:Execute",
            "garten/function/2a06b318_terasse_steckdose/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-4:Teach",
            "garten/function/2a06b318_terasse_steckdose/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-6:Teach",
            "hwr/function/67599a21_heizung_modus/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-6:Execute",
            "hwr/function/67599a21_heizung_modus/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Curtain-2:Step-Up-Down",
            "ankleide/trigger/02c04ca2_ankleide_taster_beschattung_und_luftung_2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Curtain-2:Up-Down",
            "ankleide/trigger/02c04ca2_ankleide_taster_beschattung_und_luftung_2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Curtain-3:Step-Up-Down",
            "ankleide/trigger/6daf0a92_ankleide_taster_beschattung_und_luftung_3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Curtain-3:Up-Down",
            "ankleide/trigger/6daf0a92_ankleide_taster_beschattung_und_luftung_3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-7:Teach",
            "szenen/function/3b3cf865_schlafen_beschattung/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-7:Execute",
            "szenen/function/3b3cf865_schlafen_beschattung/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-4.Switching-1:OnOff",
            "hwr/trigger/9025a2e7_taster_seiteneingang_schalten_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-1.Dimming-1:OnOff",
            "kuche/trigger/f338e543_kuche_fenster_oben_dimmen_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-5.Switching-2:OnOff",
            "flur/trigger/08efbff5_treppe_f1_schalten_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-5.Switching-1:OnOff",
            "flur/trigger/c0c54e0d_treppe_f1_schalten_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-6.Switching-2:OnOff",
            "bad/trigger/1ddfcecd_tur_oben_b1_schalten_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-1.Dimming-2:OnOff",
            "kuche/trigger/79b2d4b4_kuche_fenster_oben_dimmen_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang.Curtain-1:Up-Down",
            "buro/trigger/e2d4df5f_buro_taster_unten_beschattung_und_luftung_1/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang.Curtain-1:Step-Up-Down",
            "buro/trigger/e2d4df5f_buro_taster_unten_beschattung_und_luftung_1/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-8.Switching-1:OnOff",
            "abstellraum/trigger/e0776afb_abstellraum_taster_schalten_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-9.Switching-2:OnOff",
            "kuche/trigger/c1d9c31a_fenster_unten_k3_schalten_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-8.Switching-2:OnOff",
            "abstellraum/trigger/55b9901a_abstellraum_taster_schalten_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-9.Switching-1:OnOff",
            "kuche/trigger/f5d2698b_fenster_unten_k3_schalten_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Curtain-3:Step-Up-Down",
            "essen_wohnen/trigger/b08bd596_schiebetur_oben_w1_beschattung_und_luftung_3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Curtain-3:Up-Down",
            "essen_wohnen/trigger/b08bd596_schiebetur_oben_w1_beschattung_und_luftung_3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-20:OnOff",
            "diele/switch/15f5aee4_treppe_deckenlicht/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-19:OnOff",
            "wc/switch/8fb40c87_wc_deckenlicht/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-9.Curtain-3:Up-Down",
            "schlafen/trigger/51a260f1_schlafen_taster_tur_beschattung_und_luftung_3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-9.Curtain-3:Step-Up-Down",
            "schlafen/trigger/51a260f1_schlafen_taster_tur_beschattung_und_luftung_3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-9.Curtain-2:Up-Down",
            "schlafen/trigger/78770fbf_schlafen_taster_tur_beschattung_und_luftung_2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-9.Curtain-2:Step-Up-Down",
            "schlafen/trigger/78770fbf_schlafen_taster_tur_beschattung_und_luftung_2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-2:OnOff",
            "abstellraum/switch/01302a4e_abstellraum_steckdose/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-1:OnOff",
            "gast/switch/73a28e3b_gast_deckenlicht/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-22:OnOff",
            "wc/switch/3ae42352_wc_steckdose_laibung/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-21:OnOff",
            "diele/switch/53d04446_handlauf/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-24:OnOff",
            "vorgarten/switch/b4a2d063_steckdose_vorgarten/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Curtain-3:Up-Down",
            "kuche/trigger/544e2c06_kuchenzeile_k2_beschattung_und_luftung_3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Curtain-3:Step-Up-Down",
            "kuche/trigger/544e2c06_kuchenzeile_k2_beschattung_und_luftung_3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-4:OnOff",
            "ankleide/switch/c22a0a68_ankleide_steckdose/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-3:OnOff",
            "abstellraum/switch/8df2cd62_abstellraum_deckenlicht/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Humidity-1:HumidityStatus",
            "wc/status/36d8ce43_wc_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Roomtemperature-1:Temperature",
            "schlafen/status/05d62495_temperatur_schlafen/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-14.Roomtemperature-1:Temperature",
            "diele/status/132a89cb_diele_temperatur/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-14.Humidity-1:HumidityStatus",
            "diele/status/af6341e4_diele_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-6.Humidity-1:HumidityStatus",
            "bad/status/da28b69e_bad_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Switching-1:OnOff",
            "gast/trigger/64ca7423_gast_taster_tur_schalten_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-12.Roomtemperature-1:Temperature",
            "bad/status/bdc5fca3_bad_temperatur/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-8.Roomtemperature-1:Temperature",
            "abstellraum/status/05a9be47_abstellraum_temperatur/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-3.Roomtemperature-1:Temperature",
            "buro/status/79d58237_buro_temperatur/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Humidity-1:HumidityStatus",
            "essen_wohnen/status/b3eaa98b_wohnen_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-12.Dimming-1:OnOff",
            "bad/trigger/165bb17b_waschbecken_b3_dimmen_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Roomtemperature-1:Temperature",
            "essen_wohnen/status/8a60f079_wohnen_temperatur/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Curtain-2:Up-Down",
            "wc/trigger/43d7afee_wc_taster_beschattung_und_luftung_2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Curtain-2:Step-Up-Down",
            "wc/trigger/43d7afee_wc_taster_beschattung_und_luftung_2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Dimming-2:OnOff",
            "essen_wohnen/trigger/ef1aa331_schiebetur_oben_w1_dimmen_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Dimming-1:OnOff",
            "essen_wohnen/trigger/cc028749_schiebetur_oben_w1_dimmen_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-1:Movement",
            "wc/covering/266856c0_wc_raffstore/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-1:Up-Down",
            "wc/covering/266856c0_wc_raffstore/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-1:Position",
            "wc/covering/266856c0_wc_raffstore/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-1:Slat-Position",
            "wc/covering/266856c0_wc_raffstore/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-1:Step-Up-Down",
            "wc/covering/266856c0_wc_raffstore/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-2:Status",
            "wc/heating/e9c0839e_wc_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-2:Current",
            "wc/heating/e9c0839e_wc_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-2:Heating",
            "wc/heating/e9c0839e_wc_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-2:Set-Point",
            "wc/heating/e9c0839e_wc_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-2:Mode",
            "wc/heating/e9c0839e_wc_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-3:Current",
            "buro/heating/50b62c57_buro_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-3:Status",
            "buro/heating/50b62c57_buro_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-3:Set-Point",
            "buro/heating/50b62c57_buro_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-3:Heating",
            "buro/heating/50b62c57_buro_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-3:Mode",
            "buro/heating/50b62c57_buro_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-4:Current",
            "essen_wohnen/heating/2ba26026_wohnen_essen_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-4:Status",
            "essen_wohnen/heating/2ba26026_wohnen_essen_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-4:Set-Point",
            "essen_wohnen/heating/2ba26026_wohnen_essen_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-4:Mode",
            "essen_wohnen/heating/2ba26026_wohnen_essen_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-4:Heating",
            "essen_wohnen/heating/2ba26026_wohnen_essen_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-5:Current",
            "kuche/heating/1f67b445_kuche_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-5:Status",
            "kuche/heating/1f67b445_kuche_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-5:Set-Point",
            "kuche/heating/1f67b445_kuche_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-5:Mode",
            "kuche/heating/1f67b445_kuche_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-5:Heating",
            "kuche/heating/1f67b445_kuche_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-1:Status",
            "diele/heating/bbecb629_diele_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-1:Current",
            "diele/heating/bbecb629_diele_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-1:Set-Point",
            "diele/heating/bbecb629_diele_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-1:Heating",
            "diele/heating/bbecb629_diele_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-1:Mode",
            "diele/heating/bbecb629_diele_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Dimming-1:OnOff",
            "ankleide/trigger/dbdf5f47_ankleide_taster_dimmen_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-2:Movement",
            "buro/covering/d5a8f603_buro_raffstore_eckfenster_tur/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-2:Up-Down",
            "buro/covering/d5a8f603_buro_raffstore_eckfenster_tur/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-2:Position",
            "buro/covering/d5a8f603_buro_raffstore_eckfenster_tur/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-2:Step-Up-Down",
            "buro/covering/d5a8f603_buro_raffstore_eckfenster_tur/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-2:Slat-Position",
            "buro/covering/d5a8f603_buro_raffstore_eckfenster_tur/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-3:Up-Down",
            "buro/covering/0d4385c5_buro_raffstore_eckfenster_strasse/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-3:Step-Up-Down",
            "buro/covering/0d4385c5_buro_raffstore_eckfenster_strasse/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-3:Position",
            "buro/covering/0d4385c5_buro_raffstore_eckfenster_strasse/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-3:Slat-Position",
            "buro/covering/0d4385c5_buro_raffstore_eckfenster_strasse/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-3:Movement",
            "buro/covering/0d4385c5_buro_raffstore_eckfenster_strasse/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Curtain-2:Step-Up-Down",
            "gast/trigger/d10bdc9c_gast_taster_tur_beschattung_und_luftung_2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Curtain-2:Up-Down",
            "gast/trigger/d10bdc9c_gast_taster_tur_beschattung_und_luftung_2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-4:Up-Down",
            "buro/covering/0d237ef6_buro_raffstore_terasse/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-4:Position",
            "buro/covering/0d237ef6_buro_raffstore_terasse/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-4:Step-Up-Down",
            "buro/covering/0d237ef6_buro_raffstore_terasse/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-4:Movement",
            "buro/covering/0d237ef6_buro_raffstore_terasse/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-4:Slat-Position",
            "buro/covering/0d237ef6_buro_raffstore_terasse/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Curtain-3:Step-Up-Down",
            "schlafen/trigger/62476809_schlafen_taster_bett_beschattung_und_luftung_3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Curtain-3:Up-Down",
            "schlafen/trigger/62476809_schlafen_taster_bett_beschattung_und_luftung_3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Curtain-3:Step-Up-Down",
            "gast/trigger/168f57a8_gast_taster_tur_beschattung_und_luftung_3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Curtain-3:Up-Down",
            "gast/trigger/168f57a8_gast_taster_tur_beschattung_und_luftung_3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-5:Up-Down",
            "essen_wohnen/covering/ce82e2c1_wohnen_raffstore/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-5:Position",
            "essen_wohnen/covering/ce82e2c1_wohnen_raffstore/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-5:Step-Up-Down",
            "essen_wohnen/covering/ce82e2c1_wohnen_raffstore/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-5:Slat-Position",
            "essen_wohnen/covering/ce82e2c1_wohnen_raffstore/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-5:Movement",
            "essen_wohnen/covering/ce82e2c1_wohnen_raffstore/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-6:Up-Down",
            "essen_wohnen/covering/8755d363_essen_raffstore/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-6:Slat-Position",
            "essen_wohnen/covering/8755d363_essen_raffstore/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-6:Position",
            "essen_wohnen/covering/8755d363_essen_raffstore/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-6:Step-Up-Down",
            "essen_wohnen/covering/8755d363_essen_raffstore/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-6:Movement",
            "essen_wohnen/covering/8755d363_essen_raffstore/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-7:Slat-Position",
            "essen_wohnen/covering/61391d22_terrasse_raffstore/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-7:Up-Down",
            "essen_wohnen/covering/61391d22_terrasse_raffstore/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-7:Step-Up-Down",
            "essen_wohnen/covering/61391d22_terrasse_raffstore/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-7:Position",
            "essen_wohnen/covering/61391d22_terrasse_raffstore/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-7:Movement",
            "essen_wohnen/covering/61391d22_terrasse_raffstore/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-8:Slat-Position",
            "essen_wohnen/covering/452f4039_schiebetur_raffstore/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-8:Position",
            "essen_wohnen/covering/452f4039_schiebetur_raffstore/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-8:Step-Up-Down",
            "essen_wohnen/covering/452f4039_schiebetur_raffstore/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-8:Movement",
            "essen_wohnen/covering/452f4039_schiebetur_raffstore/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-8:Up-Down",
            "essen_wohnen/covering/452f4039_schiebetur_raffstore/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-9:Position",
            "kuche/covering/b92b3225_kuche_raffstore/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-9:Slat-Position",
            "kuche/covering/b92b3225_kuche_raffstore/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-9:Step-Up-Down",
            "kuche/covering/b92b3225_kuche_raffstore/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-9:Movement",
            "kuche/covering/b92b3225_kuche_raffstore/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-9:Up-Down",
            "kuche/covering/b92b3225_kuche_raffstore/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang.Scene-2:Scene",
            "buro/trigger/392342d5_buro_taster_unten_szene_2/scene"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-6.Scene-3:Scene",
            "diele/trigger/bf5e8401_treppe_taster_szene_3/scene"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-6:Current",
            "hwr/heating/50f16c0d_hwr_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-6:Status",
            "hwr/heating/50f16c0d_hwr_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-6:Set-Point",
            "hwr/heating/50f16c0d_hwr_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-6:Mode",
            "hwr/heating/50f16c0d_hwr_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-6:Heating",
            "hwr/heating/50f16c0d_hwr_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-9.Dimming-1:OnOff",
            "schlafen/trigger/2779325c_schlafen_taster_tur_dimmen_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-1:Status",
            "abstellraum/heating/493edf9e_abstellraum_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-1:Current",
            "abstellraum/heating/493edf9e_abstellraum_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-1:Set-Point",
            "abstellraum/heating/493edf9e_abstellraum_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-1:Heating",
            "abstellraum/heating/493edf9e_abstellraum_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-1:Mode",
            "abstellraum/heating/493edf9e_abstellraum_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-2:Mode",
            "bad/heating/7b432c66_bad_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-2:Status",
            "bad/heating/7b432c66_bad_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-2:Set-Point",
            "bad/heating/7b432c66_bad_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-2:Current",
            "bad/heating/7b432c66_bad_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-2:Heating",
            "bad/heating/7b432c66_bad_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-3:Status",
            "flur/heating/45e9c648_flur_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-3:Mode",
            "flur/heating/45e9c648_flur_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-3:Set-Point",
            "flur/heating/45e9c648_flur_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-3:Current",
            "flur/heating/45e9c648_flur_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-3:Heating",
            "flur/heating/45e9c648_flur_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-12.Curtain-3:Step-Up-Down",
            "bad/trigger/46b7196f_waschbecken_b3_beschattung_und_luftung_3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-12.Curtain-3:Up-Down",
            "bad/trigger/46b7196f_waschbecken_b3_beschattung_und_luftung_3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator6-gang2C16A2FBlindActuator3-gang-1.Switching-6:OnOff",
            "garten/switch/8a02ceef_terrasse_beleuchtung_mauer/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:RGB",
            "vorgarten/hue_light/ecf76ef2_led_streifen/rgb"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:Brightness",
            "vorgarten/hue_light/ecf76ef2_led_streifen/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:ShiftColorTemperature",
            "vorgarten/hue_light/ecf76ef2_led_streifen/shiftcolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:Shift",
            "vorgarten/hue_light/ecf76ef2_led_streifen/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:ColorTemperature",
            "vorgarten/hue_light/ecf76ef2_led_streifen/colortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:OnOff",
            "vorgarten/hue_light/ecf76ef2_led_streifen/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:RelativeBrightnessRelativeColorTemperature",
            "vorgarten/hue_light/ecf76ef2_led_streifen/relativebrightnessrelativecolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:xyY",
            "vorgarten/hue_light/ecf76ef2_led_streifen/xyy"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:Brightness",
            "essen_wohnen/hue_light/ed611c65_tischleuchte/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:RGB",
            "essen_wohnen/hue_light/ed611c65_tischleuchte/rgb"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:Shift",
            "essen_wohnen/hue_light/ed611c65_tischleuchte/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:ColorTemperature",
            "essen_wohnen/hue_light/ed611c65_tischleuchte/colortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:OnOff",
            "essen_wohnen/hue_light/ed611c65_tischleuchte/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:RelativeBrightnessRelativeColorTemperature",
            "essen_wohnen/hue_light/ed611c65_tischleuchte/relativebrightnessrelativecolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:ShiftColorTemperature",
            "essen_wohnen/hue_light/ed611c65_tischleuchte/shiftcolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:xyY",
            "essen_wohnen/hue_light/ed611c65_tischleuchte/xyy"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Switching-14:OnOff",
            "carport/switch/e775ec9a_carport_steckdose/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-6:OnOff",
            "garten/switch/c755301d_schalten_steckdose_garten/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Switching-13:OnOff",
            "vorgarten/switch/64f8e01e_haustur_steckdose/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:ColorTemperature",
            "bad/hue_light/ec362d25_bad_stern/colortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:ShiftColorTemperature",
            "bad/hue_light/ec362d25_bad_stern/shiftcolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:Shift",
            "bad/hue_light/ec362d25_bad_stern/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:Brightness",
            "bad/hue_light/ec362d25_bad_stern/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:RelativeBrightnessRelativeColorTemperature",
            "bad/hue_light/ec362d25_bad_stern/relativebrightnessrelativecolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:xyY",
            "bad/hue_light/ec362d25_bad_stern/xyy"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:OnOff",
            "bad/hue_light/ec362d25_bad_stern/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:RGB",
            "bad/hue_light/ec362d25_bad_stern/rgb"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:Brightness",
            "essen_wohnen/hue_light/ced5c94f_stern/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:RGB",
            "essen_wohnen/hue_light/ced5c94f_stern/rgb"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:ShiftColorTemperature",
            "essen_wohnen/hue_light/ced5c94f_stern/shiftcolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:Shift",
            "essen_wohnen/hue_light/ced5c94f_stern/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:ColorTemperature",
            "essen_wohnen/hue_light/ced5c94f_stern/colortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:RelativeBrightnessRelativeColorTemperature",
            "essen_wohnen/hue_light/ced5c94f_stern/relativebrightnessrelativecolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:xyY",
            "essen_wohnen/hue_light/ced5c94f_stern/xyy"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:OnOff",
            "essen_wohnen/hue_light/ced5c94f_stern/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Dimming-1:OnOff",
            "schlafen/trigger/991d40bc_schlafen_taster_bett_dimmen_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-23:OnOff",
            "carport/switch/e3ea844d_carport_abstellraum_licht/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-12.Switching-2:OnOff",
            "bad/trigger/4cb76bf6_waschbecken_b3_schalten_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-21:OnOff",
            "garten/switch/737d5f72_terrasse_steckdose/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-20:OnOff",
            "diele/switch/d4ea91d2_treppe_wand/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-24:OnOff",
            "garten/switch/e8a6ae7f_terrasse_licht/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-11.Switching-3:OnOff",
            "bad/trigger/932b761c_tur_unten_b2_schalten_3/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-3.Curtain-2:Up-Down",
            "buro/trigger/74cedbf9_buro_taster_oben_beschattung_und_luftung_2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-3.Curtain-2:Step-Up-Down",
            "buro/trigger/74cedbf9_buro_taster_oben_beschattung_und_luftung_2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-22:OnOff",
            "garten/switch/2f169373_garten_licht/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-23:OnOff",
            "vorgarten/switch/afea3a31_haustur_beleuchtung/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Curtain-3:Up-Down",
            "flur/trigger/8a11b72c_tur_gast_f2_beschattung_und_luftung_3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Curtain-3:Step-Up-Down",
            "flur/trigger/8a11b72c_tur_gast_f2_beschattung_und_luftung_3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Curtain-2:Up-Down",
            "flur/trigger/dca28477_tur_gast_f2_beschattung_und_luftung_2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Curtain-2:Step-Up-Down",
            "flur/trigger/dca28477_tur_gast_f2_beschattung_und_luftung_2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Switching-15:OnOff",
            "garten/switch/5262378e_spannungsversorgung_markise/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-19:OnOff",
            "flur/switch/b79f8661_flur_deckenlicht/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Switching-1:OnOff",
            "flur/trigger/75c7c032_tur_gast_f2_schalten_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-5:OnOff",
            "bad/switch/a4f56153_steckdose_handtuchheizung/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-11:OnOff",
            "bad/switch/f6aa694f_beleuchtung_waschtisch/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-4:Status",
            "ankleide/heating/22f41de3_ankleide_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-4:Mode",
            "ankleide/heating/22f41de3_ankleide_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-4:Set-Point",
            "ankleide/heating/22f41de3_ankleide_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-4:Current",
            "ankleide/heating/22f41de3_ankleide_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-4:Heating",
            "ankleide/heating/22f41de3_ankleide_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-14.Switching-2:OnOff",
            "diele/trigger/ae1c9e44_eingang_taster_schalten_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-14.Switching-1:OnOff",
            "diele/trigger/958c7675_eingang_taster_schalten_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-14.Switching-3:OnOff",
            "diele/trigger/fc01c620_eingang_taster_schalten_3/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-4:Movement",
            "gast/covering/af40fdc5_gast_luftung_dachfenster/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-4:Up-Down",
            "gast/covering/af40fdc5_gast_luftung_dachfenster/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-4:Step-Up-Down",
            "gast/covering/af40fdc5_gast_luftung_dachfenster/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-4:Position",
            "gast/covering/af40fdc5_gast_luftung_dachfenster/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-5:Movement",
            "ankleide/covering/628d3bbb_ankleide_luftung_dachfenster/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-5:Up-Down",
            "ankleide/covering/628d3bbb_ankleide_luftung_dachfenster/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-5:Position",
            "ankleide/covering/628d3bbb_ankleide_luftung_dachfenster/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-5:Step-Up-Down",
            "ankleide/covering/628d3bbb_ankleide_luftung_dachfenster/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-6:Movement",
            "flur/covering/00c5a5ec_flur_luftung_dachfenster/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-6:Up-Down",
            "flur/covering/00c5a5ec_flur_luftung_dachfenster/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-6:Position",
            "flur/covering/00c5a5ec_flur_luftung_dachfenster/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-6:Step-Up-Down",
            "flur/covering/00c5a5ec_flur_luftung_dachfenster/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-11.Curtain-2:Step-Up-Down",
            "bad/trigger/e466bad9_tur_unten_b2_beschattung_und_luftung_2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-11.Curtain-2:Up-Down",
            "bad/trigger/e466bad9_tur_unten_b2_beschattung_und_luftung_2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-11.Curtain-1:Step-Up-Down",
            "bad/trigger/16f34165_tur_unten_b2_beschattung_und_luftung_1/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-11.Curtain-1:Up-Down",
            "bad/trigger/16f34165_tur_unten_b2_beschattung_und_luftung_1/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-6:Set-Point",
            "schlafen/heating/209a8566_schlafen_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-6:Mode",
            "schlafen/heating/209a8566_schlafen_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-6:Status",
            "schlafen/heating/209a8566_schlafen_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-6:Heating",
            "schlafen/heating/209a8566_schlafen_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-6:Current",
            "schlafen/heating/209a8566_schlafen_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-5:Mode",
            "gast/heating/bc7e0043_gast_heizung/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-5:Status",
            "gast/heating/bc7e0043_gast_heizung/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-5:Set-Point",
            "gast/heating/bc7e0043_gast_heizung/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-5:Heating",
            "gast/heating/bc7e0043_gast_heizung/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-5:Current",
            "gast/heating/bc7e0043_gast_heizung/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-10.Switching-1:OnOff",
            "essen_wohnen/trigger/dc4a5f9c_schiebetur_unten_w3_schalten_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-1.Curtain-3:Up-Down",
            "kuche/trigger/f0fbbe0e_kuche_fenster_oben_beschattung_und_luftung_3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-1.Curtain-3:Step-Up-Down",
            "kuche/trigger/f0fbbe0e_kuche_fenster_oben_beschattung_und_luftung_3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-7.Dimming-2:OnOff",
            "essen_wohnen/trigger/e5a09d2b_wohnen_diele_w5_dimmen_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Switching-2:OnOff",
            "schlafen/trigger/9486ea0d_schlafen_taster_bett_schalten_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-7.Dimming-1:OnOff",
            "essen_wohnen/trigger/bcf0b6c9_wohnen_diele_w5_dimmen_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Humidity-1:HumidityStatus",
            "flur/status/be099ea5_flur_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-6.Switching-1:OnOff",
            "diele/trigger/65d13d51_treppe_taster_schalten_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Roomtemperature-1:Temperature",
            "gast/status/8bb7eb75_gast_temperatur/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-6.Switching-2:OnOff",
            "diele/trigger/41e838e8_treppe_taster_schalten_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Roomtemperature-1:Temperature",
            "flur/status/5e6b130b_flur_temperatur/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Switching-3:OnOff",
            "wc/trigger/b9bbd273_wc_taster_schalten_3/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-4.Roomtemperature-1:Temperature",
            "hwr/status/5e430154_temperatur/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Roomtemperature-1:Temperature",
            "ankleide/status/6c6ca57c_temperatur_ankleide/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Switching-1:OnOff",
            "wc/trigger/f519834e_wc_taster_schalten_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-6.Dimming-1:OnOff",
            "bad/trigger/40218142_tur_oben_b1_dimmen_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-3.Dimming-1:OnOff",
            "buro/trigger/18674907_buro_taster_oben_dimmen_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-4:Up-Down",
            "schlafen/covering/61900bc1_schlafen_raffstore_kl_fenster/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-4:Position",
            "schlafen/covering/61900bc1_schlafen_raffstore_kl_fenster/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-4:Step-Up-Down",
            "schlafen/covering/61900bc1_schlafen_raffstore_kl_fenster/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-4:Movement",
            "schlafen/covering/61900bc1_schlafen_raffstore_kl_fenster/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-4:Slat-Position",
            "schlafen/covering/61900bc1_schlafen_raffstore_kl_fenster/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-7:Position",
            "bad/covering/3f94e583_bad_raffstore_eckfenster_tur/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-7:Slat-Position",
            "bad/covering/3f94e583_bad_raffstore_eckfenster_tur/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-7:Step-Up-Down",
            "bad/covering/3f94e583_bad_raffstore_eckfenster_tur/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-7:Movement",
            "bad/covering/3f94e583_bad_raffstore_eckfenster_tur/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-7:Up-Down",
            "bad/covering/3f94e583_bad_raffstore_eckfenster_tur/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-8:Slat-Position",
            "bad/covering/7b5aac50_bad_raffstore_eckfenster_strasse/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-8:Step-Up-Down",
            "bad/covering/7b5aac50_bad_raffstore_eckfenster_strasse/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-8:Position",
            "bad/covering/7b5aac50_bad_raffstore_eckfenster_strasse/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-8:Movement",
            "bad/covering/7b5aac50_bad_raffstore_eckfenster_strasse/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-8:Up-Down",
            "bad/covering/7b5aac50_bad_raffstore_eckfenster_strasse/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-9:Slat-Position",
            "bad/covering/83dbf821_bad_raffstore_badewanne/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-9:Position",
            "bad/covering/83dbf821_bad_raffstore_badewanne/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-9:Step-Up-Down",
            "bad/covering/83dbf821_bad_raffstore_badewanne/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-9:Movement",
            "bad/covering/83dbf821_bad_raffstore_badewanne/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-9:Up-Down",
            "bad/covering/83dbf821_bad_raffstore_badewanne/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Humidity-1:HumidityStatus",
            "kuche/status/ed3c1972_kuche_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-10.Dimming-2:OnOff",
            "essen_wohnen/trigger/2c2319b4_schiebetur_unten_w3_dimmen_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-1:Brightness",
            "buro/dimmer/4ee7a008_buro_deckenlicht/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-1:Shift",
            "buro/dimmer/4ee7a008_buro_deckenlicht/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-1:OnOff",
            "buro/dimmer/4ee7a008_buro_deckenlicht/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Humidity-1:HumidityStatus",
            "ankleide/status/fa7ff254_ankleide_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-8.Humidity-1:HumidityStatus",
            "abstellraum/status/13662cd9_abstellraum_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-3.Humidity-1:HumidityStatus",
            "buro/status/20fff2fa_buro_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Dimming-1:OnOff",
            "kuche/trigger/87fe6385_kuchenzeile_k2_dimmen_1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Roomtemperature-1:Temperature",
            "wc/status/48dd2d65_wc_temperatur/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Dimming-2:OnOff",
            "kuche/trigger/37194dd3_kuchenzeile_k2_dimmen_2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Roomtemperature-1:Temperature",
            "kuche/status/fb56c43d_kuche_temperatur/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-4.Humidity-1:HumidityStatus",
            "hwr/status/e611b67d_hwr_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Humidity-1:HumidityStatus",
            "schlafen/status/a1052625_schlafen_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-7.Curtain-3:Up-Down",
            "essen_wohnen/trigger/de7502af_wohnen_diele_w5_beschattung_und_luftung_3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-7.Curtain-3:Step-Up-Down",
            "essen_wohnen/trigger/de7502af_wohnen_diele_w5_beschattung_und_luftung_3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Humidity-1:HumidityStatus",
            "gast/status/3c2bfe41_gast_raumfeuchte/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-1:Execute",
            "user/function/ed232cbd_wohnen_kuche_beschattung/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-1:Teach",
            "user/function/ed232cbd_wohnen_kuche_beschattung/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-3:Execute",
            "user/function/9847c734_buro_beschattung/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-3:Teach",
            "user/function/9847c734_buro_beschattung/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-2:Execute",
            "szenen/function/0f0992c4_bad_beschattung/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-2:Teach",
            "szenen/function/0f0992c4_bad_beschattung/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-2:Brightness",
            "essen_wohnen/dimmer/1c00b4ab_wohnen_beleuchtung_dimmen/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-2:Shift",
            "essen_wohnen/dimmer/1c00b4ab_wohnen_beleuchtung_dimmen/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-2:OnOff",
            "essen_wohnen/dimmer/1c00b4ab_wohnen_beleuchtung_dimmen/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-3:Brightness",
            "essen_wohnen/dimmer/ad2a835f_essen_beleuchtung_dimmen/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-3:Shift",
            "essen_wohnen/dimmer/ad2a835f_essen_beleuchtung_dimmen/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-3:OnOff",
            "essen_wohnen/dimmer/ad2a835f_essen_beleuchtung_dimmen/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-4:Shift",
            "kuche/dimmer/1a0f7ac2_kuche_dimmen_geratewand/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-4:Brightness",
            "kuche/dimmer/1a0f7ac2_kuche_dimmen_geratewand/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-4:OnOff",
            "kuche/dimmer/1a0f7ac2_kuche_dimmen_geratewand/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-1:Shift",
            "kuche/dimmer/4121b31a_kuche_dimmen_tresen/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-1:Brightness",
            "kuche/dimmer/4121b31a_kuche_dimmen_tresen/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-1:OnOff",
            "kuche/dimmer/4121b31a_kuche_dimmen_tresen/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-1:Step-Up-Down",
            "gast/covering/c02ec93f_gast_rolladen_dachfenster/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-1:Movement",
            "gast/covering/c02ec93f_gast_rolladen_dachfenster/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-1:Up-Down",
            "gast/covering/c02ec93f_gast_rolladen_dachfenster/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-1:Position",
            "gast/covering/c02ec93f_gast_rolladen_dachfenster/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-1:Up-Down",
            "essen_wohnen/trigger/05e139fd_schiebetur_mitte_w2_beschattung_und_luftung_1/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-1:Step-Up-Down",
            "essen_wohnen/trigger/05e139fd_schiebetur_mitte_w2_beschattung_und_luftung_1/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-2:Shift",
            "schlafen/dimmer/134854b1_schlafen_dimmen_deckenlicht/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-2:Brightness",
            "schlafen/dimmer/134854b1_schlafen_dimmen_deckenlicht/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-2:OnOff",
            "schlafen/dimmer/134854b1_schlafen_dimmen_deckenlicht/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-3:Movement",
            "flur/covering/142b9241_flur_rolladen_dachfenster/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-3:Up-Down",
            "flur/covering/142b9241_flur_rolladen_dachfenster/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-3:Step-Up-Down",
            "flur/covering/142b9241_flur_rolladen_dachfenster/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-3:Position",
            "flur/covering/142b9241_flur_rolladen_dachfenster/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-2:Step-Up-Down",
            "essen_wohnen/trigger/4fcf5d4e_schiebetur_mitte_w2_beschattung_und_luftung_2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-2:Up-Down",
            "essen_wohnen/trigger/4fcf5d4e_schiebetur_mitte_w2_beschattung_und_luftung_2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-2:Step-Up-Down",
            "ankleide/covering/ea84a675_ankleide_rolladen_dachfenster/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-2:Movement",
            "ankleide/covering/ea84a675_ankleide_rolladen_dachfenster/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-2:Up-Down",
            "ankleide/covering/ea84a675_ankleide_rolladen_dachfenster/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-2:Position",
            "ankleide/covering/ea84a675_ankleide_rolladen_dachfenster/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-3:Shift",
            "bad/dimmer/4eb14880_bad_dimmen_deckenlicht/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-3:Brightness",
            "bad/dimmer/4eb14880_bad_dimmen_deckenlicht/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-3:OnOff",
            "bad/dimmer/4eb14880_bad_dimmen_deckenlicht/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-3:Step-Up-Down",
            "essen_wohnen/trigger/fc4a3444_schiebetur_mitte_w2_beschattung_und_luftung_3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-3:Up-Down",
            "essen_wohnen/trigger/fc4a3444_schiebetur_mitte_w2_beschattung_und_luftung_3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-4:Brightness",
            "ankleide/dimmer/4ab988d8_ankleide_dimmen/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-4:Shift",
            "ankleide/dimmer/4ab988d8_ankleide_dimmen/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-4:OnOff",
            "ankleide/dimmer/4ab988d8_ankleide_dimmen/onoff"));
  }

  @DisplayName("should generate topic name from GiraOneDataPoint")
  @ParameterizedTest
  @MethodSource("providePairStateTopicNameOfChannelAndDataPoint")
  void topicNameFromDatapoint(String dpUrn, String expectedTopicName) {
    Optional<GiraOneDataPoint> dp = giraOneProject.lookupGiraOneDataPoint(dpUrn);
    if (dp.isPresent()) {
      assertEquals(
          String.format("g1-junit/state/%s", expectedTopicName),
          giraOneChannelMqttTopicMapper.stateTopicNameOf(dp.get()));
    } else {
      fail(String.format("Unknown dataPointUrn given: %s", dpUrn));
    }
  }

  @DisplayName("should generate GiraOneDataPoint from topic name")
  @ParameterizedTest
  @MethodSource("providePairStateTopicNameOfChannelAndDataPoint")
  void topicDatapointFromTopicName(String dpUrn, String topicName) {
    String commandTopic = String.format("g1-junit/command/%s", topicName);
    Optional<GiraOneDataPoint> dp = giraOneChannelMqttTopicMapper.giraOneDataPointOf(commandTopic);
    if (dp.isPresent()) {
      assertEquals(dpUrn, dp.get().toString());
    } else {
      fail(String.format("Unknown topicName given: %s", topicName));
    }
  }
}
