/*
 * GiraOne Bridge
 * Copyright (C) 2025 Matthias Gröger
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package de.matgroe.hassio;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;
import static org.mockito.Mockito.when;

import de.matgroe.giraone.GiraOneTestDataProvider;
import de.matgroe.giraone.client.GiraOneClient;
import de.matgroe.giraone.client.types.GiraOneDataPoint;
import de.matgroe.giraone.client.types.GiraOneProject;
import java.util.Optional;
import java.util.stream.Stream;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.mockito.Mockito;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** Testclass for @{@link HassioTopicNameMapper} */
public class HassioTopicNameMapperTest {
  private final Logger logger = LoggerFactory.getLogger(HassioTopicNameMapperTest.class);

  static GiraOneClient giraOneClient = Mockito.mock(GiraOneClient.class);

  GiraOneProject giraOneProject;

  static HassioTopicNameMapper creator;

  @BeforeAll
  static void init() {
    when(giraOneClient.getGiraOneProject())
        .thenReturn(GiraOneTestDataProvider.createGiraOneProject());
    when(giraOneClient.lookupGiraOneDeviceConfiguration())
        .thenReturn(GiraOneTestDataProvider.createGiraOneDeviceConfiguration());

    creator = new HassioTopicNameMapper("g1-junit", giraOneClient.getGiraOneProject());
  }

  @BeforeEach
  void setUp() {
    giraOneProject = giraOneClient.getGiraOneProject();
  }

  private static Stream<Arguments> providePairStateTopicNameOfChannelAndDataPoint() {
    return Stream.of(
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-6:Teach",
            "g1-junit/function-scene-6/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-6:Execute",
            "g1-junit/function-scene-6/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Curtain-2:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-13/curtain-2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Curtain-2:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-13/curtain-2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-5:Execute",
            "g1-junit/function-scene-5/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-5:Teach",
            "g1-junit/function-scene-5/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Curtain-3:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-13/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Curtain-3:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-13/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-4.Switching-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-4/switching-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-1.Dimming-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-1/dimming-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-5.Switching-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-5/switching-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-5.Switching-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-5/switching-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-6.Switching-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-6/switching-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-1.Dimming-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-1/dimming-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang.Curtain-1:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang/curtain-1/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang.Curtain-1:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang/curtain-1/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-8.Switching-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-8/switching-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-9.Switching-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-9/switching-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-8.Switching-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-8/switching-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-9.Switching-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-9/switching-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Curtain-3:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-3/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Curtain-3:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-3/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-20:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/switching-20/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-19:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/switching-19/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-9.Curtain-3:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-9/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-9.Curtain-3:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-9/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-9.Curtain-2:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-9/curtain-2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-9.Curtain-2:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-9/curtain-2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-2:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-1:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-22:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/switching-22/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-21:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/switching-21/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-24:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-24/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Curtain-3:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-2/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Curtain-3:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-2/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-4:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-4/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-3:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-3/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Humidity-1:HumidityStatus",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-8/humidity-1/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Roomtemperature-1:Temperature",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-5/roomtemperature-1/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-14.Roomtemperature-1:Temperature",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-14/roomtemperature-1/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-14.Humidity-1:HumidityStatus",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-14/humidity-1/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-6.Humidity-1:HumidityStatus",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-6/humidity-1/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Switching-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang/switching-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-12.Roomtemperature-1:Temperature",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-12/roomtemperature-1/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-8.Roomtemperature-1:Temperature",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-8/roomtemperature-1/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-3.Roomtemperature-1:Temperature",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-3/roomtemperature-1/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Humidity-1:HumidityStatus",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-3/humidity-1/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-12.Dimming-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-12/dimming-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Roomtemperature-1:Temperature",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-3/roomtemperature-1/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Curtain-2:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-8/curtain-2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Curtain-2:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-8/curtain-2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Dimming-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-3/dimming-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-3.Dimming-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-3/dimming-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-1:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-1/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-1:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-1/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-1:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-1/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-1:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-1/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-1:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-1/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-2:Status",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-2/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-2:Current",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-2/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-2:Heating",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-2/heating"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-2:Set-Point",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-2/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-2:Mode",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-2/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-3:Current",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-3/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-3:Status",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-3/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-3:Set-Point",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-3/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-3:Heating",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-3/heating"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-3:Mode",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-3/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-4:Current",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-4/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-4:Status",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-4/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-4:Set-Point",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-4/set-point"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-4:Mode",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-4/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-4:Heating",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-4/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-5:Current",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-5/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-5:Status",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-5/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-5:Set-Point",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-5/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-5:Mode",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-5/mode"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-5:Heating",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-5/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-1:Status",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-1/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-1:Current",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-1/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-1:Set-Point",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-1/set-point"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-1:Heating",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-1/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-1:Mode",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-1/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Dimming-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-13/dimming-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-2:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-2/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-2:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-2:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-2/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-2:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-2:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-2/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-3:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-3:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-3:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-3/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-3:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-3/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-3:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-3/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Curtain-2:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang/curtain-2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Curtain-2:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang/curtain-2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-4:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-4/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-4:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-4/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-4:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-4/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-4:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-4/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-4:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-4/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Curtain-3:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-5/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Curtain-3:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-5/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Curtain-3:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Curtain-3:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-5:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-5/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-5:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-5/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-5:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-5/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-5:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-5/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-5:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-5/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-6:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-6/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-6:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-6/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-6:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-6/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-6:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-6/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-6:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-6/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-7:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-7/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-7:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-7/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-7:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-7/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-7:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-7/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-7:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-7/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-8:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-8/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-8:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-8/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-8:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-8/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-8:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-8/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-8:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-8/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-9:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-9/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-9:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-9/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-9:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-9/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-9:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-9/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Curtain-9:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/curtain-9/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang.Scene-2:Scene",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang/scene-2/scene"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-6.Scene-3:Scene",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-6/scene-3/scene"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-6:Current",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-6/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-6:Status",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-6/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-6:Set-Point",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-6/set-point"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-6:Mode",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-6/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-2.Heatingactuator-6:Heating",
            "g1-junit/knxhvacactuator6-gang-2/heatingactuator-6/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-9.Dimming-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-9/dimming-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-1:Status",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-1/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-1:Current",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-1/current"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-1:Set-Point",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-1/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-1:Heating",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-1/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-1:Mode",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-1/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-2:Mode",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-2/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-2:Status",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-2/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-2:Set-Point",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-2/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-2:Current",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-2/current"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-2:Heating",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-2/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-3:Status",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-3/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-3:Mode",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-3/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-3:Set-Point",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-3/set-point"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-3:Current",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-3/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-3:Heating",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-3/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-12.Curtain-3:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-12/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-12.Curtain-3:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-12/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator6-gang2C16A2FBlindActuator3-gang-1.Switching-6:OnOff",
            "g1-junit/knxswitchingactuator6-gang2c16a2fblindactuator3-gang-1/switching-6/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:RGB", "g1-junit/hue-light-2/rgb"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:Brightness",
            "g1-junit/hue-light-2/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:ShiftColorTemperature",
            "g1-junit/hue-light-2/shiftcolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:Shift", "g1-junit/hue-light-2/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:ColorTemperature",
            "g1-junit/hue-light-2/colortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:OnOff", "g1-junit/hue-light-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:RelativeBrightnessRelativeColorTemperature",
            "g1-junit/hue-light-2/relativebrightnessrelativecolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-2:xyY", "g1-junit/hue-light-2/xyy"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:Brightness",
            "g1-junit/hue-light-1/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:RGB", "g1-junit/hue-light-1/rgb"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:Shift", "g1-junit/hue-light-1/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:ColorTemperature",
            "g1-junit/hue-light-1/colortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:OnOff", "g1-junit/hue-light-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:RelativeBrightnessRelativeColorTemperature",
            "g1-junit/hue-light-1/relativebrightnessrelativecolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:ShiftColorTemperature",
            "g1-junit/hue-light-1/shiftcolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-1:xyY", "g1-junit/hue-light-1/xyy"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Switching-14:OnOff",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/switching-14/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-6:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-6/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Switching-13:OnOff",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/switching-13/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:ColorTemperature",
            "g1-junit/hue-light-4/colortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:ShiftColorTemperature",
            "g1-junit/hue-light-4/shiftcolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:Shift", "g1-junit/hue-light-4/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:Brightness",
            "g1-junit/hue-light-4/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:RelativeBrightnessRelativeColorTemperature",
            "g1-junit/hue-light-4/relativebrightnessrelativecolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:xyY", "g1-junit/hue-light-4/xyy"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:OnOff", "g1-junit/hue-light-4/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-4:RGB", "g1-junit/hue-light-4/rgb"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:Brightness",
            "g1-junit/hue-light-3/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:RGB", "g1-junit/hue-light-3/rgb"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:ShiftColorTemperature",
            "g1-junit/hue-light-3/shiftcolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:Shift", "g1-junit/hue-light-3/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:ColorTemperature",
            "g1-junit/hue-light-3/colortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:RelativeBrightnessRelativeColorTemperature",
            "g1-junit/hue-light-3/relativebrightnessrelativecolortemperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:xyY", "g1-junit/hue-light-3/xyy"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Hue-Light-3:OnOff", "g1-junit/hue-light-3/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Dimming-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-5/dimming-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-23:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/switching-23/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-12.Switching-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-12/switching-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-21:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-21/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-20:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-20/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-1.Switching-24:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-1/switching-24/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-11.Switching-3:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-11/switching-3/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-3.Curtain-2:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-3/curtain-2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-3.Curtain-2:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-3/curtain-2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-22:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-22/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-23:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-23/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Curtain-3:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-10/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Curtain-3:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-10/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Curtain-2:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-10/curtain-2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Curtain-2:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-10/curtain-2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Switching-15:OnOff",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/switching-15/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-19:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-19/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-10.Switching-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-10/switching-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-5:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-5/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Switching-11:OnOff",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/switching-11/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-4:Status",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-4/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-4:Mode",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-4/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-4:Set-Point",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-4/set-point"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-4:Current",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-4/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-4:Heating",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-4/heating"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-14.Switching-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-14/switching-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-14.Switching-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-14/switching-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-14.Switching-3:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-14/switching-3/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-4:Movement",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-4/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-4:Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-4/up-down"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-4:Step-Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-4/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-4:Position",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-4/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-5:Movement",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-5/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-5:Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-5/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-5:Position",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-5/position"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-5:Step-Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-5/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-6:Movement",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-6/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-6:Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-6/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-6:Position",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-6/position"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-6:Step-Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-6/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-2:Step-Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-2:Movement",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-2/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-2:Slat-Position",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-2/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-2:Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-2:Position",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-2/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-11.Curtain-2:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-11/curtain-2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-11.Curtain-2:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-11/curtain-2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-11.Curtain-1:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-11/curtain-1/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-11.Curtain-1:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-11/curtain-1/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-6:Set-Point",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-6/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-6:Mode",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-6/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-6:Status",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-6/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-6:Heating",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-6/heating"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-6:Current",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-6/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-5:Mode",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-5/mode"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-5:Status",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-5/status"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-5:Set-Point",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-5/set-point"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-5:Heating",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-5/heating"),
        Arguments.of("urn:ns:invalid:invalid", "g1-junit/invalid/invalid"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxHvacActuator6-gang-1.Heatingactuator-5:Current",
            "g1-junit/knxhvacactuator6-gang-1/heatingactuator-5/current"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-10.Switching-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-10/switching-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-1.Curtain-3:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-1/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-1.Curtain-3:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-1/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-7.Dimming-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-7/dimming-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Switching-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-5/switching-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-7.Dimming-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-7/dimming-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-6.Switching-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-6/switching-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-6.Switching-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-6/switching-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Switching-3:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-8/switching-3/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Switching-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-8/switching-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-6.Dimming-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-6/dimming-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-3.Dimming-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-3/dimming-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-4:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-4/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-4:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-4/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-4:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-4/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-4:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-4/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-4:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-4/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-5:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-5/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-5:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-5/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-5:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-5/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-5:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-5/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-5:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-5/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-7:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-7/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-7:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-7/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-7:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-7/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-7:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-7/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-7:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-7/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-8:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-8/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-8:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-8/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-8:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-8/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-8:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-8/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-8:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-8/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-9:Slat-Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-9/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-9:Position",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-9/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-9:Step-Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-9/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-9:Movement",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-9/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator24-gang2C16A2FBlindActuator12-gang-2.Curtain-9:Up-Down",
            "g1-junit/knxswitchingactuator24-gang2c16a2fblindactuator12-gang-2/curtain-9/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Humidity-1:HumidityStatus",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-2/humidity-1/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-10.Dimming-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-10/dimming-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-1:Brightness",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-1/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-1:Shift",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-1/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-1:OnOff",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-13.Humidity-1:HumidityStatus",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-13/humidity-1/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-8.Humidity-1:HumidityStatus",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-8/humidity-1/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-3.Humidity-1:HumidityStatus",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-3/humidity-1/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Dimming-1:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-2/dimming-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-8.Roomtemperature-1:Temperature",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-8/roomtemperature-1/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Dimming-2:OnOff",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-2/dimming-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-2.Roomtemperature-1:Temperature",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-2/roomtemperature-1/temperature"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker2-gang-4.Humidity-1:HumidityStatus",
            "g1-junit/knxbutton4comfort2csystem55rocker2-gang-4/humidity-1/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-5.Humidity-1:HumidityStatus",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-5/humidity-1/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-7.Curtain-3:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-7/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-7.Curtain-3:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-7/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang.Humidity-1:HumidityStatus",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang/humidity-1/humiditystatus"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-1:Execute",
            "g1-junit/function-scene-1/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-1:Teach",
            "g1-junit/function-scene-1/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-3:Execute",
            "g1-junit/function-scene-3/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-3:Teach",
            "g1-junit/function-scene-3/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-2:Execute",
            "g1-junit/function-scene-2/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-2:Teach",
            "g1-junit/function-scene-2/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-4:Execute",
            "g1-junit/function-scene-4/execute"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:Function-Scene-4:Teach",
            "g1-junit/function-scene-4/teach"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-1:Step-Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-1/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-1:Movement",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-1/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-1:Slat-Position",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-1/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-1:Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-1/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-1:Position",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-1/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-2:Brightness",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-2/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-2:Shift",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-2/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-2:OnOff",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-3:Brightness",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-3/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-3:Shift",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-3/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-3:OnOff",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-3/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-4:Shift",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-4/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-4:Brightness",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-4/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-1.DimmingActuator-4:OnOff",
            "g1-junit/knxdimmingactuator4-gang-1/dimmingactuator-4/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-3:Movement",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-3/movement"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-3:Slat-Position",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-3/slat-position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-3:Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-3:Step-Up-Down",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxSwitchingActuator16-gang2C16A2FBlindActuator8-gang-1.Curtain-3:Position",
            "g1-junit/knxswitchingactuator16-gang2c16a2fblindactuator8-gang-1/curtain-3/position"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-1:Shift",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-1/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-1:Brightness",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-1/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-1:OnOff",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-1/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-1:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-4/curtain-1/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-1:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-4/curtain-1/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-2:Shift",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-2/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-2:Brightness",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-2/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-2:OnOff",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-2/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-2:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-4/curtain-2/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-2:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-4/curtain-2/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-3:Shift",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-3/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-3:Brightness",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-3/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-3:OnOff",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-3/onoff"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-3:Step-Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-4/curtain-3/step-up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxButton4Comfort2CSystem55Rocker3-gang-4.Curtain-3:Up-Down",
            "g1-junit/knxbutton4comfort2csystem55rocker3-gang-4/curtain-3/up-down"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-4:Brightness",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-4/brightness"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-4:Shift",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-4/shift"),
        Arguments.of(
            "urn:gds:dp:GiraOneServer.GIOSRVKX03:KnxDimmingActuator4-gang-2.DimmingActuator-4:OnOff",
            "g1-junit/knxdimmingactuator4-gang-2/dimmingactuator-4/onoff"));
  }

  @DisplayName("should generate topic name from GiraOneDataPoint")
  @ParameterizedTest
  @MethodSource("providePairStateTopicNameOfChannelAndDataPoint")
  void topicNameFromDatapoint(String dpUrn, String expectedTopicName) {
    Optional<GiraOneDataPoint> dp = giraOneProject.lookupGiraOneDataPoint(dpUrn);
    if (dp.isPresent()) {
      assertEquals(
          String.format("%s/state", expectedTopicName), creator.stateTopicNameOf(dp.get()));
    } else {
      fail("Invaid combination of channelUrn and dataPointUrn given");
    }
  }

  @DisplayName("should generate GiraOneDataPoint from topic name")
  @ParameterizedTest
  @MethodSource("providePairStateTopicNameOfChannelAndDataPoint")
  void topicDatapointFromTopicName(String dpUrn, String topicName) {
    Optional<GiraOneDataPoint> dp =
        creator.giraOneDataPointOf(String.format("%s/state", topicName));
    if (dp.isPresent()) {
      assertEquals(dpUrn, dp.get().toString());
    } else {
      fail("Invaid combination of channelUrn and dataPointUrn given");
    }
  }
}
